const players = [
  {
    id: 1,
    name: 'Kepa Arrizabalaga',
    position: 'goalkeepers',
    number: 1,
    img: 'https://resources.premierleague.com/premierleague/photos/players/250x250/p109745.png',
    desc: `Kepa Arrizabalaga Revuelta is a Spanish professional footballer who plays as a goalkeeper for Premier League club Chelsea and the Spain national team. He is sometimes referred to simply as Kepa. Arrizabalaga began his senior club career with Athletic Bilbao `,
  },
  {
    id: 2,
    name: 'Édouard Mendy',
    position: 'goalkeepers',
    number: 16,
    img: 'https://resources.premierleague.com/premierleague/photos/players/250x250/p228286.png',
    desc: `Édouard Osoque Mendy is a professional footballer who plays as a goalkeeper for Premier League club Chelsea and the Senegal national team. Starting his career in his native France, Mendy played in the Le Havre academy before signing professional terms with third division Cherbourg in 2011 `,
  },
  {
    id: 3,
    name: 'Thiago Silva',
    position: 'defenders',
    number: 6,
    img: 'https://resources.premierleague.com/premierleague/photos/players/110x140/p51090.png',
    desc: `Thiago Emiliano da Silva is a Brazilian professional footballer who plays as a centre-back for Premier League club Chelsea and the Brazil national team. Considered one of the greatest defenders of his generation, he is known for his defensive prowess, discipline, and leadership. `,
  },
  {
    id: 4,
    name: 'Reece James',
    position: 'defenders',
    number: 24,
    img: 'https://resources.premierleague.com/premierleague/photos/players/110x140/p225796.png',
    desc: `Reece James is an English professional footballer who plays as a right-back for Premier League club Chelsea and the England national team. `,
  },
  {
    id: 5,
    name: 'César Azpilicueta',
    position: 'defenders',
    number: 28,
    img: 'https://resources.premierleague.com/premierleague/photos/players/110x140/p41328.png',
    desc: `César Azpilicueta Tanco is a Spanish professional footballer who plays as a defender for Premier League club Chelsea, where he is also club captain, and the Spain national team. `,
  },
  {
    id: 6,
    name: 'Kalidou Koulibaly',
    position: 'defenders',
    number: 26,
    img: 'https://resources.premierleague.com/premierleague/photos/players/110x140/p86129.png',
    desc: `Kalidou Koulibaly is a professional footballer who plays as a centre-back for Premier League club Chelsea and the Senegal national team. Koulibaly began his professional club career with French team Metz in 2010, before moving to Belgian club Genk in 2012, winning the Belgian Cup in his first season `,
  },
  {
    id: 7,
    name: 'Ben Chilwell',
    position: 'defenders',
    number: 21,
    img: 'https://resources.premierleague.com/premierleague/photos/players/110x140/p172850.png',
    desc: `Benjamin James Chilwell is an English professional footballer who plays as a left-back for Premier League club Chelsea and the England national team. Beginning his career at Leicester City, Chilwell had a loan spell with Huddersfield Town and joined Chelsea in 2020.`,
  },
  {
    id: 8,
    name: 'Mateo Kovačić',
    position: 'midfielders',
    number: 8,
    img: 'https://resources.premierleague.com/premierleague/photos/players/110x140/p91651.png',
    desc: `Mateo Kovačić is a Croatian professional footballer who plays as a central midfielder for Premier League club Chelsea and the Croatia national team. Kovačić began his professional career with Dinamo Zagreb at the age of 16, with whom he won two consecutive Prva HNL titles, before joining Inter Milan in 2013. `,
  },
  {
    id: 9,
    name: "N'Golo Kanté",
    position: 'midfielders',
    number: 7,
    img: 'https://resources.premierleague.com/premierleague/photos/players/110x140/p116594.png',
    desc: `N'Golo Kanté is a French professional footballer who plays as a defensive midfielder for Premier League club Chelsea and the France national team. Considered to be one of his generation's greatest midfielders, Kanté is widely praised for his work rate and defensive acumen `,
  },
  {
    id: 10,
    name: 'Enzo Fernández',
    position: 'midfielders',
    number: 5,
    img: 'https://resources.premierleague.com/premierleague/photos/players/110x140/p448047.png',
    desc: `Enzo Jeremías Fernández is an Argentine professional footballer who plays as a central midfielder for Premier League club Chelsea and the Argentina national team. `,
  },
  {
    id: 11,
    name: 'Kai Havertz',
    position: 'midfielders',
    number: 29,
    img: 'https://resources.premierleague.com/premierleague/photos/players/110x140/p219847.png',
    desc: `Kai Lukas Havertz is a German professional footballer who plays as an attacking midfielder or forward for Premier League club Chelsea and the Germany national team. Having graduated from Bayer Leverkusen's youth academy in 2016, Havertz made his senior debut with the club at the same year.  `,
  },
  {
    id: 12,
    name: 'Raheem Sterling',
    position: 'strikers',
    number: 17,
    img: 'https://resources.premierleague.com/premierleague/photos/players/110x140/p103955.png',
    desc: `Raheem Shaquille Sterling MBE is an English professional footballer who plays as a winger and attacking midfielder for Premier League club Chelsea and the England national team. Born in Jamaica to Jamaican parents, Sterling moved to London at the age of five. `,
  },
  {
    id: 13,
    name: 'Pierre-Emerick Aubameyang',
    position: 'strikers',
    number: 9,
    img: 'https://resources.premierleague.com/premierleague/photos/players/110x140/p54694.png',
    desc: `Pierre-Emerick Emiliano François Aubameyang ONM is a professional footballer who plays as a striker for Premier League club Chelsea. He is renowned for his pace, finishing, and off-ball movement. Born in France, he is a former Gabonese international, and is the country's all-time top goalscorer.`,
  },
  {
    id: 14,
    name: 'João Félix',
    position: 'strikers',
    number: 11,
    img: 'https://resources.premierleague.com/premierleague/photos/players/110x140/p428399.png',
    desc: `João Félix Sequeira is a Portuguese professional footballer who plays as a forward for Premier League club Chelsea, on loan from Atlético Madrid of La Liga, and the Portugal national team. He can also play as a winger or an attacking midfielder. `,
  },
]
export default players
